apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: debug-pdb
spec:
  version: "{{ .TagName }}"
  homepage: https://github.com/dhenkel92/kubectl-debug-pdb
  shortDescription: "Debug Pod Disruption Budgets (PDB)"
  description: |
    This Kubernetes plugin assists in debugging pod disruption budgets.
    It helps in understanding the connection between PDBs and pods, and vice versa.
    Additionally, you can run evictions to verify if the disruption budget is functioning as anticipated.
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/dhenkel92/kubectl-debug-pdb/releases/download/{{ .TagName }}/kubectl-debug-pdb_Darwin_arm64.tar.gz" .TagName }}
    bin: kubectl-debug_pdb
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/dhenkel92/kubectl-debug-pdb/releases/download/{{ .TagName }}/kubectl-debug-pdb_Darwin_x86_64.tar.gz" .TagName }}
    bin: kubectl-debug_pdb
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    {{addURIAndSha "https://github.com/dhenkel92/kubectl-debug-pdb/releases/download/{{ .TagName }}/kubectl-debug-pdb_Linux_arm64.tar.gz" .TagName }}
    bin: kubectl-debug_pdb
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/dhenkel92/kubectl-debug-pdb/releases/download/{{ .TagName }}/kubectl-debug-pdb_Linux_x86_64.tar.gz" .TagName }}
    bin: kubectl-debug_pdb
  - selector:
      matchLabels:
        os: windows
        arch: arm64
    {{addURIAndSha "https://github.com/dhenkel92/kubectl-debug-pdb/releases/download/{{ .TagName }}/kubectl-debug-pdb_Windows_arm64.zip" .TagName }}
    bin: kubectl-debug_pdb.exe
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/dhenkel92/kubectl-debug-pdb/releases/download/{{ .TagName }}/kubectl-debug-pdb_Windows_x86_64.zip" .TagName }}
    bin: kubectl-debug_pdb.exe
