apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: debug-pdb
spec:
  # 'version' is a valid semantic version string (see semver.org). Note the prefix 'v' is required.
  version: "{{ .TagName }}"
  # 'homepage' usually links to the GitHub repository of the plugin
  homepage: https://github.com/dhenkel92/kubectl-debug-pdb
  # 'shortDescription' explains what the plugin does in only a few words
  shortDescription: "Debug and manage Pod Disruption Budgets (PDB)"
  description: |
    Pod Disruption Budgets (PDBs) help limit the number of concurrent disruptions your application experiences.
    This enhances availability while allowing the cluster administrator to manage the cluster nodes.
    Unfortunately, kubectl provides limited tooling to interact with PDBs, so this plugin aims to address this issue.
  # 'platforms' specify installation methods for various platforms (os/arch)
  # See all supported platforms below.
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/dhenkel92/kubectl-pdb/releases/download/{{ .TagName }}/kubectl-pdb_Darwin_arm64.tar.gz" .TagName }}
    bin: kubectl-debug_pdb
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/dhenkel92/kubectl-pdb/releases/download/{{ .TagName }}/kubectl-pdb_Darwin_x86_64.tar.gz" .TagName }}
    bin: kubectl-debug_pdb
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    {{addURIAndSha "https://github.com/dhenkel92/kubectl-pdb/releases/download/{{ .TagName }}/kubectl-pdb_Linux_arm64.tar.gz" .TagName }}
    bin: kubectl-debug_pdb
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/dhenkel92/kubectl-pdb/releases/download/{{ .TagName }}/kubectl-pdb_Linux_x86_64.tar.gz" .TagName }}
    bin: kubectl-debug_pdb
  - selector:
      matchLabels:
        os: windows
        arch: arm64
    {{addURIAndSha "https://github.com/dhenkel92/kubectl-pdb/releases/download/{{ .TagName }}/kubectl-pdb_Windows_arm64.zip" .TagName }}
    bin: kubectl-debug_pdb.exe
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/dhenkel92/kubectl-pdb/releases/download/{{ .TagName }}/kubectl-pdb_Windows_x86_64.zip" .TagName }}
    bin: kubectl-debug_pdb.exe
