repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
#      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/dnephin/pre-commit-golang.git
    rev: v0.3.5
    hooks:
      - id: go-fmt
      - id: go-imports
# todo: hook does not support multiple binaries in one repo
# https://github.com/dnephin/pre-commit-golang/issues/30
#      - id: go-vet
#      - id: go-lint
      - id: go-cyclo
