name: Main

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - uses: actions/setup-python@v4.3.0
        with:
          python-version: '3.10'
      - name: Install required GO libs
        run: |
          go mod download
          go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
      - uses: pre-commit/action@v3.0.0
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - name: Test
        run: make test
  release:
    runs-on: ubuntu-latest
    needs:
      - test
      - style
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - name: GoReleaser dry-run
        uses: goreleaser/goreleaser-action@v4.6.0
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
          version: latest
          args: release --skip=publish --clean --snapshot
      - name: GoReleaser publish
        uses: goreleaser/goreleaser-action@v4.6.0
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      - name: Update new version in krew-index
        uses: rajatjindal/krew-release-bot@v0.0.46
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
